version: '3.9'
services:
  database:
    image: postgres:13.3
    container_name: database
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=django
      - POSTGRES_DB=django
    volumes:
      - psql_data:/var/lib/postgresql/data
    user: "postgres"
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 1G

  backend:
    container_name: container_backend
    build:
      context: ./lib_catalog
    restart: unless-stopped
    ports:
      - 8000:8000
    user: "www-data"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - private
      - public
    healthcheck:
      test: curl --fail -s http://localhost:8000/admin || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 3G

  frontend:
    container_name: container_frontend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - public

volumes:
  psql_data:

secrets:
  db-password:
    file: pass.txt

networks:
  public: {}
  private: {}